apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: rencecaringal000-hello-internet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
